import './globals.css'


export const metadata = {
  title: 'DocMec',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/img/loogo.png" />
      <body >{children}</body>
    </html>
  )
}
